In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
pip show scikit-learn

Name: scikit-learn
Version: 1.5.2
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License: BSD 3-Clause License

Copyright (c) 2007-2024 The scikit-learn developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: C:\Users\Bjsan\AppData\Roaming\Python\Python311\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: daal4py, imbalanced-learn, scikit-learn-intelex
Note: you may need to restart the kernel to use updated packages.

DEPRECATION: Loading egg at c:\programdata\anaconda3\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..

In [40]:
import chardet

# Leer los primeros 10,000 bytes para detectar la codificación
with open('C:/Users/Bjsan/OneDrive/Escritorio/4semestre/DW/analisiscasas/modelo2/house_data/house_data.csv', 'rb') as f:
    resultado = chardet.detect(f.read(10000))

print(f"Codificación detectada: {resultado['encoding']}")

Codificación detectada: ascii

In [41]:
casas_df = pd.read_csv('C:/Users/Bjsan/OneDrive/Escritorio/4semestre/DW/analisiscasas/modelo2/house_data/house_data.csv', encoding='ISO-8859-1')

Data Frame

In [42]:
casas_df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [43]:
df_casas = casas_df.drop(['sqft_living15','sqft_lot15','id','date','lat','long',], axis=1)

In [44]:
df_casas

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144

In [45]:
for columna in df_casas.columns:
    valor_mas_comun = df_casas[columna].mode()[0] if not df_casas[columna].isna().all() else None
    promedio = df_casas[columna].mean() if pd.api.types.is_numeric_dtype(df_casas[columna]) else None
    print(f"Columna: {columna}")
    print(f"  Valor más común: {valor_mas_comun}")
    print(f"  Promedio: {promedio}")

Columna: price
  Valor más común: 350000.0
  Promedio: 540088.1417665294
Columna: bedrooms
  Valor más común: 3
  Promedio: 3.37084162309721
Columna: bathrooms
  Valor más común: 2.5
  Promedio: 2.1147573219821405
Columna: sqft_living
  Valor más común: 1300
  Promedio: 2079.8997362698374
Columna: sqft_lot
  Valor más común: 5000
  Promedio: 15106.967565816869
Columna: floors
  Valor más común: 1.0
  Promedio: 1.4943089807060566
Columna: waterfront
  Valor más común: 0
  Promedio: 0.007541757275713691
Columna: view
  Valor más común: 0
  Promedio: 0.23430342849211122
Columna: condition
  Valor más común: 3
  Promedio: 3.4094295100171195
Columna: grade
  Valor más común: 7
  Promedio: 7.656873178179799
Columna: sqft_above
  Valor más común: 1300
  Promedio: 1788.3906907879516
Columna: sqft_basement
  Valor más común: 0
  Promedio: 291.5090454818859
Columna: yr_built
  Valor más común: 2014
  Promedio: 1971.0051357978994
Columna: yr_renovated
  Valor más común: 0
  Promedio: 84.40225790033776
Columna: zipcode
  Valor más común: 98103
  Promedio: 98077.93980474715

In [46]:
df_casas.isna().sum().sort_values(ascending = False)

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
dtype: int64

## MODELO PREDICTORIO

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from joblib import dump

In [48]:
# Seleccionar las características (X) y la variable objetivo (y)
X = df_casas.drop(columns=['price'])  # 'precio' es la variable que queremos predecir
y = df_casas['price']

In [49]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [50]:
# Crear el modelo
model = RandomForestRegressor(random_state=42)

# Entrenar el modelo
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [51]:
# Predecir en el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el modelo
mae = mean_absolute_error(y_test, y_pred)
print(f"Error absoluto medio (MAE): {mae}")

Error absoluto medio (MAE): 91608.16600514087

In [52]:
# Ejemplo: predecir el precio de una nueva propiedad
nueva_propiedad = X_test.iloc[7:8]  # Usar datos del conjunto de prueba como ejemplo
prediccion = model.predict(nueva_propiedad)
print(f"El precio predicho para la nueva propiedad es: {prediccion[0]}")

El precio predicho para la nueva propiedad es: 525320.0

In [53]:
nueva_propiedad

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode
19369,3,2.5,1800,4400,1.0,0,0,5,7,1350,450,1970,0,98199

In [54]:
# Calcular R^2
r2 = model.score(X_test, y_test)
print(f"Coeficiente de determinación (R^2): {r2}")

Coeficiente de determinación (R^2): 0.7852453459386908

In [55]:
dump(model, 'modelo_entrenado_analisis_casas.joblib')
print("Modelo guardado exitosamente.")

Modelo guardado exitosamente.